### ISSUE TITLE
Stop wallet to mine XDAGs

### ISSUE THREAD

**Issue by xdager** [XDagger/xdagj#19]
**Title**
stop wallet to mine xdag

**Software information (please complete the following information)**
- OS version : [eg. MacOS BigSur 11.1.2]
- XDAGJ version  : [eg. XDAGJ-0.4.1-Aplha]
- JDK version : [eg. JDK15.0.2]

**Describe the bug**
When a wallet connects a pool, the pool will give little XDAGs to the wallet and generate transactions every minute. 

**Expected behavior**
The pool should not give XDAGs to the wallet as a reward. The pool should close the TCP immediately after the wallet checks the balance, sends the transaction, and confirms the transaction.

**Actual behavior**
When a wallet connects a pool, the pool will give little XDAGs to the wallet and generate transactions every minute. 

**Log**
Provide detailed logs so that we can troubleshoot problems.

**Can Reproduce(option)**
If can ,If you can, please tell us the detailed steps:
1. Go to 'www.xdag.io'
2. Download a windows version wallet
3. Connects to the pool

**Additional context**

**Comment by Holt666** [comment]
fix on 0.5.0
