### ISSUE TITLE
Looking for a develepment roadmap

### ISSUE THREAD

**Issue by shiyi23** [XDagger/xdagj#3]
I have some time to do some contribute, but there is no develepment roapmap in this repo, can communities offer a roadmap so that other develeper like me can join the xdagj more easily？

**Comment by iGodPro** [comment]
> I have some time to do some contribute, but there is no develepment roapmap in this repo, can communities offer a roadmap so that other develeper like me can join the xdagj more easily？

HI, I'm iGod from XDAG Community , our XDAG DEV will reply and offer you the roadmap.
we all glad that you can join us. 
and  do you want to join our  community's wechat group ?It is more convenient to communicate XDAG's technology.

**Comment by MyronX** [comment]
> I have some time to do some contribute, but there is no develepment roapmap in this repo, can communities offer a roadmap so that other develeper like me can join the xdagj more easily？

Hi,Bro. U can view the roadmap here https://github.com/XDagger/xdagj/blob/master/docs/XDAGJ_Roadmap.md .
U can choose what you are interested in and join us.

**Comment by shiyi23** [comment]
> > I have some time to do some contribute, but there is no develepment roapmap in this repo, can communities offer a roadmap so that other develeper like me can join the xdagj more easily？
> 
> Hi,Bro. U can view the roadmap here https://github.com/XDagger/xdagj/blob/master/docs/XDAGJ_Roadmap.md .
> U can choose what you are interested in and join us.

Thanks,bro.
