### ISSUE TITLE
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'void io.xdag.crypto.jni.Native.dfslib_random_init()'

### ISSUE THREAD

**Issue by wangxuguo** [XDagger/xdagj#4]
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'void io.xdag.crypto.jni.Native.dfslib_random_init()'
at mac when run a pool.

**Comment by MyronX** [comment]
> Exception in thread "main" java.lang.UnsatisfiedLinkError: 'void io.xdag.crypto.jni.Native.dfslib_random_init()'
> at mac when run a pool.

You can try to perform the following operations
1. Delete  src/c/libdfs.dylib and src/main/resources/native/libdfs.dylib in project;
2. `cd src/c & make_so.sh `
to rebuild a dynamic link library
If the problem persists, please let us know the detailed error log and the version number of the system you are using

**Comment by wangxuguo** [comment]
Thanks.  But there is still a lot of issues, state is Pool Initializing....   always.

**Comment by MyronX** [comment]
The latest code fixes some problems, you can try to run with the new code.
