### ISSUE TITLE
 Transfer amount problem

### ISSUE THREAD

**Issue by Wawa1996** [XDagger/xdagj#6]
1.Transfer issues: When there are input areas where the transfer amount needs to be greater than or equal to 6 as input blocks, it will cause the fields of a transaction block to not store information such as input and signature, resulting in an abnormal transaction block.
2. When transferring money, a transaction requires multiple transaction blocks to publish, but only one transaction block will be broadcast, resulting in only one transaction amount that is actually received.

**Comment by punk8** [comment]
Large-value situations need to be divided into multiple transaction blocks. Currently, the simplest method is used to achieve this, which is to simply divide the multiple inputs equally, and then create multiple transaction blocks
