### ISSUE TITLE
Suggestions: too many transaction blocks are generated when the block reward is distributed

### ISSUE THREAD

**Issue by MyronX** [XDagger/xdagj#9]
Pool will distribute rewards to each miner, and a large number of transaction blocks will be generated for each epoch.
The idea of ​​the solution is as follows:
1)The reward amount less than 10^-9 will not be paid;
2)Each miner reward reaches 1 XDAG before paying；
3)The miner's offline time is greater than the specified time, the reward will be cleared.

**Comment by Holt666** [comment]
fix on 0.5.0
